name: smart_student_assistant_rags
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  latlong2: ^0.9.1
  flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/profile.png
    - images/ecole-image.jpg
